### ISSUE TITLE
Bug: Property window does not scroll down all the way

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#245] opened 2022-06-29 09:06 UTC
<img width="311" alt="image" src="https://user-images.githubusercontent.com/74647806/176398063-a20c9fc1-4961-4774-b455-07b94c050ee0.png">

tested with multiple models and all are cut at the bottom

**Comment by pablo-mayrgundter** [comment] 2022-07-27 13:52
Yeah, confirmed.  Looks like it's close.. e.g. on https://bldrs.ai/share/v/gh/Swiss-Property-AG/Portfolio/main/KNIK.ifc/88/111/153/3768/171418 the last PSet does just have 7 components as seen in the DOM inspector:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/2480879/181264029-b0284b17-7443-4f3d-8dc9-6fcceecb3097.png">

**Comment by pablo-mayrgundter** [comment] 2022-08-17 00:53
Fixed in #333 i believe.

**Closed** 2023-01-11 14:57 UTC
Labels: bug
