### ISSUE TITLE
LFS: Public model opens fine when logged in but not without being logged in

### ISSUE THREAD

**Issue by MarkusSteinbrecher** [bldrs-ai/Share#686] opened 2023-03-27 07:56 UTC
Trying to open this [model](https://bldrs.ai/share/v/gh/Swiss-Property-AG/Unteraegeri-Public/main/Unteraegeri.ifc) which is hosted by Github LFS and it works fine if I am logged in on Bldrs but throws an error message if I try to open it without being logged in:$

![image](https://user-images.githubusercontent.com/74647806/227877161-070d43d0-b8a1-4e89-a62d-84d7488dfef4.png)

![image](https://user-images.githubusercontent.com/74647806/227877304-f236cada-deb5-4f24-986a-8ebbc84c5322.png)

Any idea? Is this related to the other OAuth bug? Am I doing something wrong or is this a bug? 

Thanks!

**Comment by OlegMoshkovich** [comment] 2023-03-27 08:58
Same for me, getting the error when not logged in, but can get to it through the file browser.
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/3433606/227893368-2cc4a06f-9e25-4aa6-ab3a-f69031e660e2.png">

**Comment by oo-bldrs** [comment] 2023-03-27 14:28
@OlegMoshkovich @pablo-mayrgundter In order to address this, we need to come to a decision on how to handle specific, read-only GitHub API operations for application users who are not logged in, given that an individual's limit is no more than 60 requests per hour.

Also, this issue is a duplicate of the original GitHub LFS issue (#277).

**Comment by pablo-mayrgundter** [comment] 2023-03-27 17:40
This file is only 35MB, so LFS not needed.  Workaround for now is to recreate the repo without LFS.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/2480879/228022330-2fcaf501-52b8-4e45-9d2c-53187adcab1f.png">

**Comment by OlegMoshkovich** [comment] 2023-03-27 18:05
Created a test repo with the file.
It opens ok for me.
https://bldrs.ai/share/v/gh/OlegMoshkovich/Unteraegeri--test/main/Unteraegeri.ifc#c:165.955,122.104,149.039,37.207,-6.643,20.291

@MarkusSteinbrecher please test.

**Comment by MarkusSteinbrecher** [comment] 2023-03-27 19:29
Thanks! It works fine without LFS and for public. The reasoning behind LFS is, that we will need LFS for every project at some point so it is easier to setup the Github Repo for LFS when it is created. We can work around that for most models for now but this one here is very hard to make small for example: https://bldrs.ai/share/v/gh/Swiss-Property-AG/Eggstock/main/Eggstock_INTERN.ifc (still private but I can give you access). So, would still be great if that issue is solved.

**Comment by oo-bldrs** [comment] 2023-05-03 17:41
@MarkusSteinbrecher Do you have a URL to a model that's publicly available in a Git LFS-enabled repository?

**Comment by MarkusSteinbrecher** [comment] 2023-05-04 13:10
Not at the moment ... do you want me to create one?

**Comment by oo-bldrs** [comment] 2023-05-04 13:12
@MarkusSteinbrecher I would appreciate it, if you could.

I have a potential fix and I'd like to test before we claim success.

**Comment by MarkusSteinbrecher** [comment] 2023-05-04 13:36
here you go: https://github.com/Swiss-Property-AG/Turmfalke-Test/blob/main/Turmfalke-Test.ifc

and it opens fine if logged in and doesn't if not.

**Comment by oo-bldrs** [comment] 2023-05-04 13:45
The potential fix seems to work...

https://deploy-preview-717--bldrs-share.netlify.app/share/v/gh/Swiss-Property-AG/Turmfalke-Test/main/Turmfalke-Test.ifc

**Comment by MarkusSteinbrecher** [comment] 2023-05-04 13:48
Yes! You can claim success :)

**Closed** 2023-05-04 16:57 UTC

**Comment by oo-bldrs** [comment] 2023-05-04 17:07
Pushed live: https://bldrs.ai/share/v/gh/Swiss-Property-AG/Turmfalke-Test/main/Turmfalke-Test.ifc
